KorpaZaKupovinu/urls.py
from django.urls import path
from . import views

app_name = 'korpazakupovinu'

urlpatterns = [
    path('', views.DetaljiKorpe, name='DetaljiKorpe'),
    path('dodaj/<int:trotinet_id>/',
         views.DodajUKorpu, name='DodajUKorpu'),
    path('ukloni/<int:trotinet_id>/',
         views.UkloniIzKorpe, name='UkloniIzKorpe'),
]

Porudzbina/urls.py
from django.urls import path
from . import views

app_name = 'porudzbine'
urlpatterns = [
    path('kreirajporudzbinu/',
         views.KreiranjePorudzbine, name='KreiranjePorudzbine'),
]

ProdajaTrotineta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KorpaZaKupovinu/', include('KorpaZaKupovinu.urls', namespace='KorpaZaKupovinu')),
    path('Porudzbina/', include('Porudzbina.urls', namespace='Porudzbina')),
    path('', include('ProdavnicaTrotineta.urls', namespace='ProdavnicaTrotineta')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProdavnicaTrotineta/urls.py
from django.urls import path
from . import views

app_name = 'prodavnicatrotineta'

urlpatterns = [path('', views.ListaTrotineta, name='ListaTrotineta'), path('<slug:segment_slug>/', views.ListaTrotineta, name='ListaTrotinetaPoSegmentu'), path('<int:id>/<slug:slug>/', views.DetaljiTrotineta, name='DetaljiTrotineta')]

KorpaZaKupovinu/models.py
from django.db import models

# Create your models here.

Porudzbina/models.py
from django.db import models
from ProdavnicaTrotineta.models import Trotinet


class Porudzbina(models.Model):
    ime = models.CharField(max_length=50)
    prezime = models.CharField(max_length=50)
    email = models.EmailField()
    adresa = models.CharField(max_length=250)
    postanski_broj = models.CharField(max_length=20)
    grad = models.CharField(max_length=100)
    datum_kreiranja = models.DateTimeField(auto_now_add=True)
    datum_azuriranja = models.DateTimeField(auto_now=True)
    placeno = models.BooleanField(default=True)

    class Meta:
        ordering = ('-datum_kreiranja',)
        verbose_name = 'porudzbina'
        verbose_name_plural = 'porudzbine'

    def __str__(self):
        return f'Porudzbina {self.id}'

    def UzmiUkupnuCenuPorudzbine(self):
        return sum(stavka.UzmiCenu() for stavka in self.stavka_porudzbine_p.all())


class StavkaPorudzbine(models.Model):
    porudzbina = models.ForeignKey(Porudzbina,
                                   related_name='stavke_porudzbine_p',
                                   on_delete=models.CASCADE)
    trotinet = models.ForeignKey(Trotinet,
                                  related_name='stavke_porudzbine_a',
                                  on_delete=models.CASCADE)
    cena = models.DecimalField(max_digits=10, decimal_places=2)
    kolicina = models.PositiveIntegerField(default=1)

    def __str__(self): return str(self.id)

    def UzmiCenu(self): return self.cena * self.kolicina

ProdavnicaTrotineta/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Segment(models.Model):
    naziv = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('naziv',)
        verbose_name = 'segment'
        verbose_name_plural = 'segmenti'

    def __str__(self):
        return self.naziv

    def ApsolutniURL(self):
        return reverse('ProdavnicaTrotineta:ListaTrotinetaPoSegmentu', args=[self.slug])


class Trotinet(models.Model):
    segment = models.ForeignKey(Segment, related_name='trotineti', on_delete=models.CASCADE)
    naziv = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    slika = models.ImageField(upload_to='trotinet/%Y/%m/%d', blank=True)
    opis = models.TextField(blank=True)
    cena = models.DecimalField(max_digits=10,decimal_places=2)
    raspoloziv = models.BooleanField(default=True)
    kreiran = models.DateTimeField(auto_now_add=True)
    azuriran = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('naziv',)
        index_together = (('id', 'slug'),)
        verbose_name_plural = 'trotineti'

    def __str__(self):
        return self.naziv
    def ApsolutniURL(self):
        return reverse('ProdavnicaTrotineta:DetaljiTrotineta', args=[self.id, self.slug])

KorpaZaKupovinu/forms.py
from django import forms

IZBOR_BROJA_TROTINETA = [(i, str(i)) for i in range(1, 11)]

class FormaZaDodavanjeTrotinetaUKorpu(forms.Form):
    kolicina = forms.TypedChoiceField(choices = IZBOR_BROJA_TROTINETA, empty_value=1, coerce=int)
    dodati_na_kolicinu = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

Porudzbina/forms.py
from django import forms
from .models import Porudzbina

class FormaZaPorudzbinu(forms.ModelForm):
    class Meta:
        model = Porudzbina
        fields = ['ime', 'prezime', 'email', 'adresa', 'postanski_broj', 'grad']

KorpaZaKupovinu/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ProdavnicaTrotineta.models import Trotinet
from .korpa import Korpa
from .forms import FormaZaDodavanjeTrotinetaUKorpu

@require_POST
def DodajUKorpu(request, trotinet_id):
    korpa = Korpa(request)
    trotinet = get_object_or_404(Trotinet, id=trotinet_id)
    form = FormaZaDodavanjeTrotinetaUKorpu(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        korpa.Dodaj(trotinet=trotinet, kolicina=cd['kolicina'], dodati_na_kolicinu=cd['dodati_na_kolicinu'])

    return redirect('KorpaZaKupovinu:DetaljiKorpe')

@require_POST
def UkloniIzKorpe(request, trotinet_id):
    korpa = Korpa(request)
    trotinet = get_object_or_404(Trotinet, id=trotinet_id)
    korpa.Ukloni(trotinet)
    return redirect('KorpaZaKupovinu:DetaljiKorpe')


def DetaljiKorpe(request):
    korpa = Korpa(request)
    for stavka in korpa:
        stavka['formazaazuriranjekolicine'] = FormaZaDodavanjeTrotinetaUKorpu(initial={'kolicina': 1, 'dodati_na_kolicinu': True})
    return render(request, 'KorpaZaKupovinu/detail.html', {'korpa': korpa})

Porudzbina/views.py
from django.shortcuts import render

# Create your views here.


from KorpaZaKupovinu.korpa import Korpa
from .models import StavkaPorudzbine
from .forms import FormaZaPorudzbinu

def KreiranjePorudzbine(request):
    korpa = Korpa(request)

    if request.method == 'POST':
        forma = FormaZaPorudzbinu(request.POST)

        if forma.is_valid():
            porudzbina = forma.save()

            for stavka in korpa:
                StavkaPorudzbine.objects.create(porudzbina=porudzbina, trotinet=stavka['trotinet'], cena=stavka['cena'], kolicina=stavka['kolicina'])

            korpa.ObrisiJeIzSesije()

            return render(request, 'Porudzbina/created.html', {'porudzbina': porudzbina})

    else:
        forma = FormaZaPorudzbinu()
    return render(request, 'Porudzbina/create.html', {'korpa': korpa, 'forma': forma})

ProdavnicaTrotineta/views.py
from django.shortcuts import render, get_object_or_404
from .models import Segment,Trotinet

from KorpaZaKupovinu.forms import FormaZaDodavanjeTrotinetaUKorpu
from KorpaZaKupovinu.korpa import Korpa

def ListaTrotineta(request, segment_slug = None):
    segment = None
    segmenti = Segment.objects.all()
    trotineti = Trotinet.objects.filter(raspoloziv=True)
    if segment_slug:
        segment = get_object_or_404(Segment, slug=segment_slug)
        trotineti = trotineti.filter(segment=segment)
    korpa = Korpa(request)
    return render(request, 'ProdavnicaTrotineta/Trotinet/list.html', {'segment': segment, 'segmenti': segmenti, 'trotineti': trotineti, 'korpa':korpa})

def DetaljiTrotineta(request, id, slug):
    trotinet = get_object_or_404(Trotinet, id=id, slug = slug, raspoloziv = True)

    korpa = Korpa(request)
    formazadodavanjetrotinetaukorpu = FormaZaDodavanjeTrotinetaUKorpu()

    return render(request, 'ProdavnicaTrotineta/Trotinet/detail.html', {'trotinet': trotinet, 'formazadodavanjetrotinetaukorpu': formazadodavanjetrotinetaukorpu, 'korpa': korpa})

KorpaZaKupovinu/templates/KorpaZaKupovinu/detail.html
{% extends "ProdavnicaTrotineta/base.html" %}
{% load static %}
{% block title %} Korpa za kupovinu {% endblock %}
{% block content %}
<h1>Korpa za kupovinu</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Slika</th>
        <th>Trotinet</th>
        <th>Kolicina</th>
        <th>Ukloni iz korpe</th>
        <th>Cena po komadu</th>
        <th>Cena</th>
    </tr>
    </thead>
    <tbody>
    {% for stavka in korpa %}
    {% with trotinet=stavka.trotinet %}
    <tr>
        <td>
            <a href="{{ trotinet.ApsolutniURL }}">
                <img src="{% if trotinet.slika %}{{ trotinet.slika.url }}
                            {% else %}{% static 'img\\no_image.png' %}{% endif %}">
            </a>
        </td>
        <td>{{ trotinet.naziv }}</td>
        <td>
            <form action="{% url 'KorpaZaKupovinu:DodajUKorpu' trotinet.id %}" method="post">
            {{ stavka.formazaazuriranjekolicine.kolicina }}
            {{ stavka.formazaazuriranjekolicine.dodati_na_kolicinu }}
            <input type="submit" value="Azuriraj">
            {% csrf_token %}
            </form>
        </td>
        <td>
            <form action="{% url 'KorpaZaKupovinu:UkloniIzKorpe' trotinet.id %}" method="post">
            <input type="submit" value="Ukloni">
            {% csrf_token %}
            </form>
        </td>
        <td class="num">${{ stavka.cena }}</td>
        <td class="num">${{ stavka.ukupna_cena }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ korpa.UzmiUkupnuCenu }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'ProdavnicaTrotineta:ListaTrotineta' %}" class="button light">Nastavak kupovine</a>
    <a href="{% url 'Porudzbina:KreiranjePorudzbine' %}" class="button">Provera</a>
</p>
{% endblock %}

Porudzbina/templates/Porudzbina/create.html
{% extends "ProdavnicaTrotineta/base.html" %}
{% block title %}
Provera
{% endblock %}
{% block content %}
<h1>Provera</h1>
<div class="order-info">
    <h3>Vasa porudzbina</h3>
    <ul>
        {% for stavka in korpa %}
        <li>
            {{ stavka.kolicina }}x {{ stavka.trotinet.naziv }}
            <span>&euro;{{ stavka.ukupna_cena }}</span>
        </li>
        {% endfor %}
    </ul>
    <p>Total: ${{ korpa.UzmiUkupnuCenu }}</p>
</div>
<form method="post" class="order-form">
    {{ forma.as_p }}
    <p><input type="submit" value="Narucivanje"></p>
    {% csrf_token %}
</form>
{% endblock %}

Porudzbina/templates/Porudzbina/created.html
{% extends "ProdavnicaTrotineta/base.html" %}
{% block title %}
Hvala Vam
{% endblock %}
{% block content %}
<h1>HVALA</h1>
<p>Vasa porudzbina broj <strong>{{ porudzbina.id }}</strong> je uspesno
    kompletirana.</p>
{% endblock %}

ProdavnicaTrotineta/templates/ProdavnicaTrotineta/Trotinet/detail.html
{% extends "ProdavnicaTrotineta/base.html" %}
{% load static %}
{% block title %}
{{ trotinet.naziv }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if trotinet.slika %}{{ trotinet.slika.url }}
{% else %} {% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ trotinet.naziv }}</h1>
    <h2>
        <a href="{{ trotinet.segment.ApsolutniURL }}">
            {{ trotinet.segment }}
        </a>
    </h2>
    <p class="price">&euro;{{ trotinet.cena }}</p>
    <!-- dodato za korpu-->
    <form action="{% url 'KorpaZaKupovinu:DodajUKorpu' trotinet.id %}"
    method="post">
    {{ formazadodavanjetrotinetaukorpu }}
    {% csrf_token %}
    <input type="submit" value="Dodaj u korpu">
    </form>
    {{ trotinet.opis|linebreaks }}
</div>
{% endblock %}

ProdavnicaTrotineta/templates/ProdavnicaTrotineta/Trotinet/list.html
{% extends "ProdavnicaTrotineta/base.html" %}
{% load static %}
{% block title %} {% if segment %}{{ segment.naziv }}{% else %}Trotineti{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar"><h3>Segmenti</h3>
    <ul>
        <li {% if not segment %}class="selected" {% endif %}>
            <a href="{% url 'ProdavnicaTrotineta:ListaTrotineta' %}">All</a> </li>
        {% for c in segmenti %}
        <li {% if segment.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.ApsolutniURL }}">{{ c.naziv }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if segment %}{{ segment.naziv }}{% else %}Trotineti{% endif %}</h1>
    {% for trotinet in trotineti %}
    <div class="item">
        <a href="{{ trotinet.ApsolutniURL }}">
            <img src="{% if trotinet.slika %}{{ trotinet.slika.url }}
{% else %}{% static 'img/no_image.png' %}{% endif %}"></a>
        <a href="{{ trotinet.ApsolutniURL }}">{{ trotinet.naziv }}</a>
        <br>
        &euro;{{ trotinet.cena }}
    </div>
    {% endfor %}
</div>
{% endblock %} 

ProdavnicaTrotineta/templates/ProdavnicaTrotineta/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Prodavnica trotineta{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>

<div id="header"><a href="/" class="logo">Prodavnica trotineta</a></div>
<div id="subheader">
    <div class="cart">
        {{korpa|length}}
        {% with brojstavkiukorpi=korpa|length %}
        {% if brojstavkiukorpi > 0 %}
        U korpi se nalazi:
        <a href="{% url 'KorpaZaKupovinu:DetaljiKorpe' %}">
        {{brojstavkiukorpi}} kom, ukupna cena &euro;{{ korpa.UzmiUkupnuCenu }}
        </a>
        {% else %}
        Korpa je prazna.
        {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>